using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MetanetA_MobileApp.Model;
using MetanetA_MobileApp.Services;
using MetanetA_MobileApp.Services.Abstractions;
using MetanetA_MobileApp.View.Products;


namespace MetanetA_MobileApp.ViewModels;

/// <summary>
/// Personal Cabinet screen VM – holds the user's personal data and actions.
/// All property/command names are in English as requested.
/// </summary>
public partial class ProfileViewModel : ObservableObject
{
    // Backing fields are generated by [ObservableProperty].
    // Initial values are just examples; replace with real data source.



    // Optional: track whether there are unsaved changes.
    [ObservableProperty] private bool hasChanges;
    [ObservableProperty] IUserSession userSession;
    // When any property changes, mark HasChanges = true.
   //partial void OnNameChanged(string value) => HasChanges = true;
   //partial void OnSurnameChanged(string value) => HasChanges = true;
   //partial void OnCityChanged(string value) => HasChanges = true;
   //partial void OnFatherNameChanged(string value) => HasChanges = true;
   //partial void OnJobChanged(string value) => HasChanges = true;
   //partial void OnPhoneNumberChanged(string value) => HasChanges = true;
   //partial void OnBirthDateChanged(DateTime value) => HasChanges = true;
   //partial void OnVillageChanged(string value) => HasChanges = true;

    public ProfileViewModel(IUserSession userSession)
    {
        this.userSession = userSession;
        HasChanges = false;
    }

    /// <summary>
    /// Save the profile (persist to your API / local DB / state service).
    /// </summary>
    [RelayCommand]
    private async Task Save()
    {
        // TODO: Replace with real persistence (API call, state service, etc.).
        HasChanges = false;
        await Shell.Current.DisplayAlert("Saved", "Your profile has been saved.", "OK");
    }

    /// <summary>
    /// Reset form to the last known defaults (for demo purposes).
    /// </summary>
    [RelayCommand]
    private void Reset()
    {
 
        HasChanges = false;
    }
    [RelayCommand]
    public async Task Qr()
    {
       await BottomMenuFunctions.Qr();
    }

    [RelayCommand]
    public async Task Home()
    {
        await BottomMenuFunctions.Home();
    }
 
    [RelayCommand]
    public async Task Products()
    {
        await Shell.Current.GoToAsync($"//{nameof(ProductPage)}");
    }
}
